<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

namespace GPBMetadata;

class Sample
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aab010a0c73616d706c652e70726f746f120767726565746572221c0a0c" .
            "48656c6c6f52657175657374120c0a046e616d65180120012809221d0a0a" .
            "48656c6c6f5265706c79120f0a076d65737361676518012001280932430a" .
            "074772656574657212380a0853617948656c6c6f12152e67726565746572" .
            "2e48656c6c6f526571756573741a132e677265657465722e48656c6c6f52" .
            "65706c79220042085a062e3b67727063620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

